crm/urls.py
from django.urls import path
from crm import views as v

app_name = 'crm'


urlpatterns = [
    # path('', v.person_list, name='person_list'),
    # path('<int:pk>/', v.person_detail, name='person_detail'),
    # path('create/', v.person_create, name='person_create'),
    # path('<int:pk>/update/', v.person_update, name='person_update'),
    # path('<int:pk>/delete/', v.person_delete, name='person_delete'),
    path('', v.PersonListView.as_view(), name='person_list'),
    path('<int:pk>/', v.PersonDetailView.as_view(), name='person_detail'),
    path('create/', v.PersonCreateView.as_view(), name='person_create'),
    path('<int:pk>/update/', v.PersonUpdateView.as_view(), name='person_update'),
    path('<int:pk>/delete/', v.PersonDeleteView.as_view(), name='person_delete'),
]

crm/models.py
from django.db import models
from django.urls import reverse_lazy
from core.models import Active, Address, Document, TimeStampedModel


class Person(TimeStampedModel, Address, Document, Active):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField('sobrenome', max_length=50, null=True, blank=True)  # noqa E501
    email = models.EmailField(null=True, blank=True)

    class Meta:
        ordering = ('first_name',)
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name or ""}'.strip()

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return reverse_lazy('crm:person_detail', kwargs={'pk': self.pk})

    def get_fields_verbose_names(self):
        return [{'name': field.verbose_name, 'value': getattr(self, field.name)} for field in self._meta.fields]

crm/forms.py
from django import forms

from .models import Person


class PersonForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Person
        # fields = '__all__'
        fields = (
            'first_name',
            'last_name',
            'email',
            'address',
            'address_number',
            'complement',
            'district',
            'city',
            'uf',
            'cep',
            'country',
            'cpf',
            'rg',
            'cnh',
            'active',
        )

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['active'].widget.attrs['class'] = None

crm/views.py
from django.db.models import Q
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from .forms import PersonForm
from .mixins import SearchMixin
from .models import Person


def person_list(request):
    template_name = 'crm/person_list.html'
    object_list = Person.objects.all()

    search = request.GET.get('search')
    if search:
        object_list = object_list.filter(
            Q(first_name__icontains=search) |
            Q(last_name__icontains=search) |
            Q(email__icontains=search)
        )

    context = {'object_list': object_list}
    return render(request, template_name, context)


def person_detail(request, pk):
    template_name = 'crm/person_detail.html'
    obj = Person.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


def person_create(request):
    template_name = 'crm/person_form.html'
    form = PersonForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('crm:person_list')

    context = {'form': form}
    return render(request, template_name, context)


def person_update(request, pk):
    template_name = 'crm/person_form.html'
    instance = Person.objects.get(pk=pk)
    form = PersonForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('crm:person_list')

    context = {'form': form}
    return render(request, template_name, context)


def person_delete(request, pk):
    template_name = 'crm/person_confirm_delete.html'
    obj = Person.objects.get(pk=pk)

    if request.method == 'POST':
        obj.delete()
        return redirect('crm:person_list')

    context = {'object': obj}
    return render(request, template_name, context)


class PersonListView(SearchMixin, ListView):
    model = Person
    paginate_by = 10


class PersonDetailView(DetailView):
    model = Person


class PersonCreateView(CreateView):
    model = Person
    form_class = PersonForm


class PersonUpdateView(UpdateView):
    model = Person
    form_class = PersonForm


class PersonDeleteView(DeleteView):
    model = Person
    success_url = reverse_lazy('crm:person_list')

crm/templates/crm/person_confirm_delete.html
<!-- person_delete.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Deletar</h1>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'crm:person_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

crm/templates/crm/person_detail.html
<!-- person_detail.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Detalhes de {{ object }}</h1>

  <ul>
    {% for field in object.get_fields_verbose_names %}
      <li><b>{{ field.name }}:</b> {{ field.value|default:'---' }}</li>
    {% endfor %}
  </ul>
{% endblock content %}

crm/templates/crm/person_form.html
<!-- person_form.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Formulário</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

crm/templates/crm/person_list.html
<!-- person_list.html -->
{% extends "base.html" %}

{% block content %}
<div>
  <div class="row">
    <div class="col-auto">
      <h1>Lista de Pessoas</h1>
    </div>
    <div class="col-auto">
      <a class="btn btn-primary" href="{% url 'crm:person_create' %}">Adicionar</a>
    </div>
    <div class="col">
      <form action="." method="GET" class="form-inline">
        <div class="form-group flex-grow-1">
          <input id="id_search" name="search" class="form-control flex-grow-1" type="text" placeholder="Buscar..." />
        </div>
        <div class="form-group pl-2">
          <button type="submit" class="btn btn-success">Buscar</button>
        </div>
        <div class="form-group pl-2">
          <a class="btn btn-link" href=".">Limpar</a>
        </div>
      </form>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
      <tr>
        <td>
          <a href="{{ object.get_absolute_url }}">{{ object.full_name }}</a>
        </td>
        <td>{{ object.email|default:'---' }}</td>
        <td>
          <a href="{% url 'crm:person_update' object.pk %}">
            <i class="fa fa-edit"></i>
          </a>
          <a href="{% url 'crm:person_delete' object.pk %}" class="pl-2">
            <i class="fa fa-close no"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% include "includes/pagination.html" %}

{% endblock content %}